name: outliersvsfreq_test_env
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.4
  - cudatoolkit
  - pytorch=1.10
  - torchvision=0.11.2
  - torchaudio
  - torchmetrics
  - ipykernel
  - seaborn
  - scipy
  - spacy
  - scikit-learn
  - matplotlib
  - pip:
    - transformers==4.16
    - datasets
    - tokenizers
    - blingfire
    - tensorflow