name: outliersvsfreq
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.2.4
  - cudatoolkit=11.3
  - pytorch
  - torchvision
  - torchaudio
  - torchmetrics
  - ipykernel
  - seaborn
  - scipy
  - spacy
  - scikit-learn
  - matplotlib
  - pip:
    - transformers==4.16
    - datasets
    - tokenizers
    - blingfire
    - tensorflow